---
name: Super-Linter

on:
  # Run this workflow every time a new commit pushed to main branch
  push:
    branches: [main]
  # Run this workflow every time a new PR to main or develop branch
  pull_request:
    branches: [main, develop]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of
          # changed files within `super-linter`
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          JAVASCRIPT_DEFAULT_STYLE: prettier
