name: Super-Linter

on:
  # Run this workflow every time a new commit pushed to main branch
  push:
    branches: [main]
  # Run this workflow every time a new PR to main or develop branch
  pull_request:
    branches: [main, develop]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: install modules
        run: |
          npm ci

      ################################
      # Run Linter against code base #
      ################################
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          CSS_FILE_NAME: .stylelintrc.json
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          YAML_CONFIG_FILE: .yamllint.yaml
          JAVASCRIPT_DEFAULT_STYLE: prettier
